server:
  port: 18080
nacos:
  config:
    server-addr: 192.168.1.126:8011
dubbo:
  application:
    name: dubbo-gateway
sentinel:
  config:
    nacos:
      serveraddr: 192.168.1.126:8011
      dataid: dubbo-gateway-flow-rules
      groupid: SENTINEL_GROUP
route:
  config:
    nacos:
      serveraddr: 192.168.1.126:8011
      dataid: routes-config
      groupid: GATEWAY_GROUP